/*
 * This file is part of the TrinityCore Project. See AUTHORS file for Copyright information
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

// Classic 1.60: ports of VMaNGOS scripts. Script names carry a "classic_" prefix (world DB ScriptName) so they never
// collide with TC's own scripts; sql/custom/world assigns them to the vanilla creatures / gameobjects / instances.

void AddSC_classic_elwynn_forest();
void AddSC_classic_npc_sandstalker();
void AddSC_classic_boss_ossirian();
void AddSC_classic_boss_moam();
void AddSC_classic_boss_buru();
void AddSC_classic_boss_ayamiss();
void AddSC_classic_boss_kurinnaxx();
void AddSC_classic_ruins_of_ahnqiraj();
void AddSC_classic_instance_ruins_of_ahnqiraj();
void AddSC_classic_boss_kelthuzad();
void AddSC_classic_boss_sapphiron();
void AddSC_classic_boss_thaddius();
void AddSC_classic_boss_gluth();
void AddSC_classic_boss_grobbulus();
void AddSC_classic_boss_patchwerk();
void AddSC_classic_boss_four_horsemen();
void AddSC_classic_boss_gothik();
void AddSC_classic_boss_razuvious();
void AddSC_classic_boss_loatheb();
void AddSC_classic_boss_heigan();
void AddSC_classic_boss_noth();
void AddSC_classic_boss_maexxna();
void AddSC_classic_boss_faerlina();
void AddSC_classic_boss_anubrekhan();
void AddSC_classic_instance_naxxramas();
void AddSC_classic_boss_victor_nefarius();
void AddSC_classic_boss_nefarian();
void AddSC_classic_boss_flamegor();
void AddSC_classic_boss_firemaw();
void AddSC_classic_boss_ebonroc();
void AddSC_classic_boss_chromaggus();
void AddSC_classic_boss_broodlord_lashlayer();
void AddSC_classic_boss_vaelastrasz();
void AddSC_classic_boss_razorgore();
void AddSC_classic_instance_blackwing_lair();
void AddSC_classic_boss_ouro();
void AddSC_classic_boss_viscidus();
void AddSC_classic_boss_twinemperors();
void AddSC_classic_boss_cthun();
void AddSC_classic_zulgurub_trash();
void AddSC_classic_instance_zulgurub();
void AddSC_classic_boss_venoxis();
void AddSC_classic_boss_renataki();
void AddSC_classic_boss_marli();
void AddSC_classic_boss_mandokir();
void AddSC_classic_boss_jindo();
void AddSC_classic_boss_jeklik();
void AddSC_classic_boss_hakkar();
void AddSC_classic_boss_gahzranka();
void AddSC_classic_boss_arlokk();
void AddSC_classic_boss_huhuran();
void AddSC_classic_boss_fankriss();
void AddSC_classic_boss_sartura();
void AddSC_classic_boss_bug_trio();
void AddSC_classic_boss_skeram();
void AddSC_classic_mob_anubisath_sentinel();
void AddSC_classic_instance_temple_of_ahnqiraj();
void AddSC_classic_boss_sulfuron_harbinger();
void AddSC_classic_boss_shazzrah();
void AddSC_classic_boss_ragnaros();
void AddSC_classic_boss_majordomo_executus();
void AddSC_classic_boss_lucifron();
void AddSC_classic_boss_golemagg();
void AddSC_classic_boss_gehennas();
void AddSC_classic_boss_garr();
void AddSC_classic_boss_baron_geddon();
void AddSC_classic_molten_core();
void AddSC_classic_instance_molten_core();
void AddSC_classic_boss_onyxia();
void AddSC_classic_instance_onyxia_lair();
void AddSC_classic_boss_tomb_of_seven();
void AddSC_classic_boss_magmus();
void AddSC_classic_boss_high_interrogator_gerstahn();
void AddSC_classic_boss_grizzle();
void AddSC_classic_boss_gorosh_the_dervish();
void AddSC_classic_boss_general_angerforge();
void AddSC_classic_boss_emperor_dagran_thaurissan();
void AddSC_classic_boss_anubshiah();
void AddSC_classic_arena_challenge_ai();
void AddSC_classic_blackrock_depths();
void AddSC_classic_instance_blackrock_depths();
void AddSC_classic_dreadsteed_ritual();
void AddSC_classic_boss_zevrim();
void AddSC_classic_boss_tendris_warpwood();
void AddSC_classic_boss_immol_thar();
void AddSC_classic_boss_gordok_king();
void AddSC_classic_instance_dire_maul();
void AddSC_classic_boss_archaedas();
void AddSC_classic_boss_ironaya();
void AddSC_classic_uldaman();
void AddSC_classic_instance_uldaman();
void AddSC_classic_boss_thermaplugg();
void AddSC_classic_gnomeregan();
void AddSC_classic_instance_gnomeregan();
void AddSC_classic_razorfen_downs();
void AddSC_classic_instance_razorfen_downs();
void AddSC_classic_razorfen_kraul();
void AddSC_classic_instance_razorfen_kraul();
void AddSC_classic_boss_noxxion();
void AddSC_classic_boss_landslide();
void AddSC_classic_boss_celebras_the_cursed();
void AddSC_classic_instance_maraudon();
void AddSC_classic_zulfarrak();
void AddSC_classic_instance_zulfarrak();
void AddSC_classic_sunken_temple();
void AddSC_classic_instance_sunken_temple();
void AddSC_classic_boss_interrogator_vishas();
void AddSC_classic_boss_houndmaster_loksey();
void AddSC_classic_boss_high_inquisitor_fairbanks();
void AddSC_classic_boss_herod();
void AddSC_classic_boss_arcanist_doan();
void AddSC_classic_instance_scarlet_monastery();
void AddSC_classic_ubrs_trash();
void AddSC_classic_boss_warmaster_voone();
void AddSC_classic_boss_urok();
void AddSC_classic_boss_the_beast();
void AddSC_classic_boss_shadow_hunter_voshgajin();
void AddSC_classic_boss_overlord_wyrmthalak();
void AddSC_classic_boss_highlord_omokk();
void AddSC_classic_boss_halycon();
void AddSC_classic_instance_blackrock_spire();
void AddSC_classic_scholo_trash();
void AddSC_classic_boss_vectus();
void AddSC_classic_boss_the_ravenian();
void AddSC_classic_boss_ras_frostwhisper();
void AddSC_classic_boss_lorekeeper_polkelt();
void AddSC_classic_boss_lord_alexei_barov();
void AddSC_classic_boss_jandice_barov();
void AddSC_classic_boss_instructor_malicia();
void AddSC_classic_boss_illucia_barov();
void AddSC_classic_boss_doctor_theolen_krastinov();
void AddSC_classic_instance_scholomance();
void AddSC_classic_boss_timmy_the_cruel();
void AddSC_classic_boss_ramstein_the_gorger();
void AddSC_classic_boss_postmaster_malown();
void AddSC_classic_boss_order_of_silver_hand();
void AddSC_classic_boss_nerubenkan();
void AddSC_classic_boss_maleki_the_pallid();
void AddSC_classic_boss_magistrate_barthilas();
void AddSC_classic_boss_dathrohan_balnazzar();
void AddSC_classic_boss_cannon_master_willey();
void AddSC_classic_boss_baroness_anastari();
void AddSC_classic_stratholme();
void AddSC_classic_instance_stratholme();
void AddSC_classic_wailing_caverns();
void AddSC_classic_instance_wailing_caverns();
void AddSC_classic_instance_blackfathom_deeps();
void AddSC_classic_instance_shadowfang_keep();
void AddSC_classic_boss_mr_smite();
void AddSC_classic_deadmines();
void AddSC_classic_instance_deadmines();
void AddSC_classic_moonglade();
void AddSC_classic_feralas();
void AddSC_classic_felwood();
void AddSC_classic_dustwallow_marsh();
void AddSC_classic_desolace();
void AddSC_classic_darkshore();
void AddSC_classic_ashenvale();
void AddSC_classic_hillsbrad_foothills();
void AddSC_classic_eastern_plaguelands();
void AddSC_classic_duskwood();
void AddSC_classic_dun_morogh();
void AddSC_classic_burning_steppes();
void AddSC_classic_blasted_lands();
void AddSC_classic_arathi_highlands();
void AddSC_classic_winterspring();
void AddSC_classic_ungoro_crater();
void AddSC_classic_thousand_needles();
void AddSC_classic_the_barrens();
void AddSC_classic_tanaris();
void AddSC_classic_stonetalon_mountains();
void AddSC_classic_silithus();
void AddSC_classic_world_event_wareffort();
void AddSC_classic_npcs_special();
void AddSC_classic_go_scripts();
void AddSC_classic_spell_scripts();
void AddSC_classic_armory_commands();
void AddSC_classic_legacy_commands();
void AddSC_classic_discord_commands();
void AddSC_classic_wetlands();
void AddSC_classic_westfall();
void AddSC_classic_western_plaguelands();
void AddSC_classic_swamp_of_sorrows();
void AddSC_classic_stranglethorn_vale();
void AddSC_classic_stormwind_rendezvous();
void AddSC_classic_stormwind_city();
void AddSC_classic_silverpine_forest();
void AddSC_classic_searing_gorge();
void AddSC_classic_loch_modan();
void AddSC_classic_hinterlands();

void AddClassicScripts()
{
    AddSC_classic_elwynn_forest();
    AddSC_classic_npc_sandstalker();
    AddSC_classic_boss_ossirian();
    AddSC_classic_boss_moam();
    AddSC_classic_boss_buru();
    AddSC_classic_boss_ayamiss();
    AddSC_classic_boss_kurinnaxx();
    AddSC_classic_ruins_of_ahnqiraj();
    AddSC_classic_instance_ruins_of_ahnqiraj();
    AddSC_classic_boss_kelthuzad();
    AddSC_classic_boss_sapphiron();
    AddSC_classic_boss_thaddius();
    AddSC_classic_boss_gluth();
    AddSC_classic_boss_grobbulus();
    AddSC_classic_boss_patchwerk();
    AddSC_classic_boss_four_horsemen();
    AddSC_classic_boss_gothik();
    AddSC_classic_boss_razuvious();
    AddSC_classic_boss_loatheb();
    AddSC_classic_boss_heigan();
    AddSC_classic_boss_noth();
    AddSC_classic_boss_maexxna();
    AddSC_classic_boss_faerlina();
    AddSC_classic_boss_anubrekhan();
    AddSC_classic_instance_naxxramas();
    AddSC_classic_boss_victor_nefarius();
    AddSC_classic_boss_nefarian();
    AddSC_classic_boss_flamegor();
    AddSC_classic_boss_firemaw();
    AddSC_classic_boss_ebonroc();
    AddSC_classic_boss_chromaggus();
    AddSC_classic_boss_broodlord_lashlayer();
    AddSC_classic_boss_vaelastrasz();
    AddSC_classic_boss_razorgore();
    AddSC_classic_instance_blackwing_lair();
    AddSC_classic_boss_ouro();
    AddSC_classic_boss_viscidus();
    AddSC_classic_boss_twinemperors();
    AddSC_classic_boss_cthun();
    AddSC_classic_zulgurub_trash();
    AddSC_classic_instance_zulgurub();
    AddSC_classic_boss_venoxis();
    AddSC_classic_boss_renataki();
    AddSC_classic_boss_marli();
    AddSC_classic_boss_mandokir();
    AddSC_classic_boss_jindo();
    AddSC_classic_boss_jeklik();
    AddSC_classic_boss_hakkar();
    AddSC_classic_boss_gahzranka();
    AddSC_classic_boss_arlokk();
    AddSC_classic_boss_huhuran();
    AddSC_classic_boss_fankriss();
    AddSC_classic_boss_sartura();
    AddSC_classic_boss_bug_trio();
    AddSC_classic_boss_skeram();
    AddSC_classic_mob_anubisath_sentinel();
    AddSC_classic_instance_temple_of_ahnqiraj();
    AddSC_classic_boss_sulfuron_harbinger();
    AddSC_classic_boss_shazzrah();
    AddSC_classic_boss_ragnaros();
    AddSC_classic_boss_majordomo_executus();
    AddSC_classic_boss_lucifron();
    AddSC_classic_boss_golemagg();
    AddSC_classic_boss_gehennas();
    AddSC_classic_boss_garr();
    AddSC_classic_boss_baron_geddon();
    AddSC_classic_molten_core();
    AddSC_classic_instance_molten_core();
    AddSC_classic_boss_onyxia();
    AddSC_classic_instance_onyxia_lair();
    AddSC_classic_boss_tomb_of_seven();
    AddSC_classic_boss_magmus();
    AddSC_classic_boss_high_interrogator_gerstahn();
    AddSC_classic_boss_grizzle();
    AddSC_classic_boss_gorosh_the_dervish();
    AddSC_classic_boss_general_angerforge();
    AddSC_classic_boss_emperor_dagran_thaurissan();
    AddSC_classic_boss_anubshiah();
    AddSC_classic_arena_challenge_ai();
    AddSC_classic_blackrock_depths();
    AddSC_classic_instance_blackrock_depths();
    AddSC_classic_dreadsteed_ritual();
    AddSC_classic_boss_zevrim();
    AddSC_classic_boss_tendris_warpwood();
    AddSC_classic_boss_immol_thar();
    AddSC_classic_boss_gordok_king();
    AddSC_classic_instance_dire_maul();
    AddSC_classic_boss_archaedas();
    AddSC_classic_boss_ironaya();
    AddSC_classic_uldaman();
    AddSC_classic_instance_uldaman();
    AddSC_classic_boss_thermaplugg();
    AddSC_classic_gnomeregan();
    AddSC_classic_instance_gnomeregan();
    AddSC_classic_razorfen_downs();
    AddSC_classic_instance_razorfen_downs();
    AddSC_classic_razorfen_kraul();
    AddSC_classic_instance_razorfen_kraul();
    AddSC_classic_boss_noxxion();
    AddSC_classic_boss_landslide();
    AddSC_classic_boss_celebras_the_cursed();
    AddSC_classic_instance_maraudon();
    AddSC_classic_zulfarrak();
    AddSC_classic_instance_zulfarrak();
    AddSC_classic_sunken_temple();
    AddSC_classic_instance_sunken_temple();
    AddSC_classic_boss_interrogator_vishas();
    AddSC_classic_boss_houndmaster_loksey();
    AddSC_classic_boss_high_inquisitor_fairbanks();
    AddSC_classic_boss_herod();
    AddSC_classic_boss_arcanist_doan();
    AddSC_classic_instance_scarlet_monastery();
    AddSC_classic_ubrs_trash();
    AddSC_classic_boss_warmaster_voone();
    AddSC_classic_boss_urok();
    AddSC_classic_boss_the_beast();
    AddSC_classic_boss_shadow_hunter_voshgajin();
    AddSC_classic_boss_overlord_wyrmthalak();
    AddSC_classic_boss_highlord_omokk();
    AddSC_classic_boss_halycon();
    AddSC_classic_instance_blackrock_spire();
    AddSC_classic_scholo_trash();
    AddSC_classic_boss_vectus();
    AddSC_classic_boss_the_ravenian();
    AddSC_classic_boss_ras_frostwhisper();
    AddSC_classic_boss_lorekeeper_polkelt();
    AddSC_classic_boss_lord_alexei_barov();
    AddSC_classic_boss_jandice_barov();
    AddSC_classic_boss_instructor_malicia();
    AddSC_classic_boss_illucia_barov();
    AddSC_classic_boss_doctor_theolen_krastinov();
    AddSC_classic_instance_scholomance();
    AddSC_classic_boss_timmy_the_cruel();
    AddSC_classic_boss_ramstein_the_gorger();
    AddSC_classic_boss_postmaster_malown();
    AddSC_classic_boss_order_of_silver_hand();
    AddSC_classic_boss_nerubenkan();
    AddSC_classic_boss_maleki_the_pallid();
    AddSC_classic_boss_magistrate_barthilas();
    AddSC_classic_boss_dathrohan_balnazzar();
    AddSC_classic_boss_cannon_master_willey();
    AddSC_classic_boss_baroness_anastari();
    AddSC_classic_stratholme();
    AddSC_classic_instance_stratholme();
    AddSC_classic_wailing_caverns();
    AddSC_classic_instance_wailing_caverns();
    AddSC_classic_instance_blackfathom_deeps();
    AddSC_classic_instance_shadowfang_keep();
    AddSC_classic_boss_mr_smite();
    AddSC_classic_deadmines();
    AddSC_classic_instance_deadmines();
    AddSC_classic_moonglade();
    AddSC_classic_feralas();
    AddSC_classic_felwood();
    AddSC_classic_dustwallow_marsh();
    AddSC_classic_desolace();
    AddSC_classic_darkshore();
    AddSC_classic_ashenvale();
    AddSC_classic_hillsbrad_foothills();
    AddSC_classic_eastern_plaguelands();
    AddSC_classic_duskwood();
    AddSC_classic_dun_morogh();
    AddSC_classic_burning_steppes();
    AddSC_classic_blasted_lands();
    AddSC_classic_arathi_highlands();
    AddSC_classic_winterspring();
    AddSC_classic_ungoro_crater();
    AddSC_classic_thousand_needles();
    AddSC_classic_the_barrens();
    AddSC_classic_tanaris();
    AddSC_classic_stonetalon_mountains();
    AddSC_classic_silithus();
    AddSC_classic_world_event_wareffort();
    AddSC_classic_npcs_special();
    AddSC_classic_go_scripts();
    AddSC_classic_spell_scripts();
    AddSC_classic_armory_commands();
    AddSC_classic_legacy_commands();
    AddSC_classic_discord_commands();
    AddSC_classic_wetlands();
    AddSC_classic_westfall();
    AddSC_classic_western_plaguelands();
    AddSC_classic_swamp_of_sorrows();
    AddSC_classic_stranglethorn_vale();
    AddSC_classic_stormwind_rendezvous();
    AddSC_classic_stormwind_city();
    AddSC_classic_silverpine_forest();
    AddSC_classic_searing_gorge();
    AddSC_classic_loch_modan();
    AddSC_classic_hinterlands();
}
